### ISSUE TITLE
pgadmin4 installs in "current user" mode

### ISSUE THREAD

**Issue by TobiX** [coldacid/chocolatey-packages#1]
It seems the installer (sometimes?) need a `/allusers` flag to install into `Program Files` - for me it currently installs into `c:\Users\Administrator\AppData\Local\Programs\pgAdmin 4\v6\` and only adds it to the Administrator start menu...

**Comment by charabaruk** [comment]
Yeah, that must be something new since version 6. I've not used pgAdmin in a while, so I never noticed this.

I'll have to look into this during my staycation next week.
